// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// This is a placeholder file. Run: protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative internal/native/proto/native.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// NativeServiceClient is the client API for NativeService service.
type NativeServiceClient interface {
	// Video methods
	VideoSetSleepMode(ctx context.Context, in *VideoSetSleepModeRequest, opts ...grpc.CallOption) (*Empty, error)
	VideoGetSleepMode(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VideoGetSleepModeResponse, error)
	VideoSleepModeSupported(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VideoSleepModeSupportedResponse, error)
	VideoSetQualityFactor(ctx context.Context, in *VideoSetQualityFactorRequest, opts ...grpc.CallOption) (*Empty, error)
	VideoGetQualityFactor(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VideoGetQualityFactorResponse, error)
	VideoSetEDID(ctx context.Context, in *VideoSetEDIDRequest, opts ...grpc.CallOption) (*Empty, error)
	VideoGetEDID(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VideoGetEDIDResponse, error)
	VideoLogStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VideoLogStatusResponse, error)
	VideoStop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	VideoStart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// UI methods
	GetLVGLVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetLVGLVersionResponse, error)
	UIObjHide(ctx context.Context, in *UIObjHideRequest, opts ...grpc.CallOption) (*UIObjHideResponse, error)
	UIObjShow(ctx context.Context, in *UIObjShowRequest, opts ...grpc.CallOption) (*UIObjShowResponse, error)
	UISetVar(ctx context.Context, in *UISetVarRequest, opts ...grpc.CallOption) (*Empty, error)
	UIGetVar(ctx context.Context, in *UIGetVarRequest, opts ...grpc.CallOption) (*UIGetVarResponse, error)
	UIObjAddState(ctx context.Context, in *UIObjAddStateRequest, opts ...grpc.CallOption) (*UIObjAddStateResponse, error)
	UIObjClearState(ctx context.Context, in *UIObjClearStateRequest, opts ...grpc.CallOption) (*UIObjClearStateResponse, error)
	UIObjAddFlag(ctx context.Context, in *UIObjAddFlagRequest, opts ...grpc.CallOption) (*UIObjAddFlagResponse, error)
	UIObjClearFlag(ctx context.Context, in *UIObjClearFlagRequest, opts ...grpc.CallOption) (*UIObjClearFlagResponse, error)
	UIObjSetOpacity(ctx context.Context, in *UIObjSetOpacityRequest, opts ...grpc.CallOption) (*UIObjSetOpacityResponse, error)
	UIObjFadeIn(ctx context.Context, in *UIObjFadeInRequest, opts ...grpc.CallOption) (*UIObjFadeInResponse, error)
	UIObjFadeOut(ctx context.Context, in *UIObjFadeOutRequest, opts ...grpc.CallOption) (*UIObjFadeOutResponse, error)
	UIObjSetLabelText(ctx context.Context, in *UIObjSetLabelTextRequest, opts ...grpc.CallOption) (*UIObjSetLabelTextResponse, error)
	UIObjSetImageSrc(ctx context.Context, in *UIObjSetImageSrcRequest, opts ...grpc.CallOption) (*UIObjSetImageSrcResponse, error)
	DisplaySetRotation(ctx context.Context, in *DisplaySetRotationRequest, opts ...grpc.CallOption) (*DisplaySetRotationResponse, error)
	UpdateLabelIfChanged(ctx context.Context, in *UpdateLabelIfChangedRequest, opts ...grpc.CallOption) (*Empty, error)
	UpdateLabelAndChangeVisibility(ctx context.Context, in *UpdateLabelAndChangeVisibilityRequest, opts ...grpc.CallOption) (*Empty, error)
	SwitchToScreenIf(ctx context.Context, in *SwitchToScreenIfRequest, opts ...grpc.CallOption) (*Empty, error)
	SwitchToScreenIfDifferent(ctx context.Context, in *SwitchToScreenIfDifferentRequest, opts ...grpc.CallOption) (*Empty, error)
	// Testing
	DoNotUseThisIsForCrashTestingOnly(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// Events stream
	StreamEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (NativeService_StreamEventsClient, error)
}

type nativeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNativeServiceClient(cc grpc.ClientConnInterface) NativeServiceClient {
	return &nativeServiceClient{cc}
}

func (c *nativeServiceClient) VideoSetSleepMode(ctx context.Context, in *VideoSetSleepModeRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/native.NativeService/VideoSetSleepMode", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) VideoGetSleepMode(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VideoGetSleepModeResponse, error) {
	out := new(VideoGetSleepModeResponse)
	err := c.cc.Invoke(ctx, "/native.NativeService/VideoGetSleepMode", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) VideoSleepModeSupported(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VideoSleepModeSupportedResponse, error) {
	out := new(VideoSleepModeSupportedResponse)
	err := c.cc.Invoke(ctx, "/native.NativeService/VideoSleepModeSupported", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) VideoSetQualityFactor(ctx context.Context, in *VideoSetQualityFactorRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/native.NativeService/VideoSetQualityFactor", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) VideoGetQualityFactor(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VideoGetQualityFactorResponse, error) {
	out := new(VideoGetQualityFactorResponse)
	err := c.cc.Invoke(ctx, "/native.NativeService/VideoGetQualityFactor", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) VideoSetEDID(ctx context.Context, in *VideoSetEDIDRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/native.NativeService/VideoSetEDID", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) VideoGetEDID(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VideoGetEDIDResponse, error) {
	out := new(VideoGetEDIDResponse)
	err := c.cc.Invoke(ctx, "/native.NativeService/VideoGetEDID", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) VideoLogStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VideoLogStatusResponse, error) {
	out := new(VideoLogStatusResponse)
	err := c.cc.Invoke(ctx, "/native.NativeService/VideoLogStatus", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) VideoStop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/native.NativeService/VideoStop", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) VideoStart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/native.NativeService/VideoStart", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) GetLVGLVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetLVGLVersionResponse, error) {
	out := new(GetLVGLVersionResponse)
	err := c.cc.Invoke(ctx, "/native.NativeService/GetLVGLVersion", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) UIObjHide(ctx context.Context, in *UIObjHideRequest, opts ...grpc.CallOption) (*UIObjHideResponse, error) {
	out := new(UIObjHideResponse)
	err := c.cc.Invoke(ctx, "/native.NativeService/UIObjHide", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) UIObjShow(ctx context.Context, in *UIObjShowRequest, opts ...grpc.CallOption) (*UIObjShowResponse, error) {
	out := new(UIObjShowResponse)
	err := c.cc.Invoke(ctx, "/native.NativeService/UIObjShow", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) UISetVar(ctx context.Context, in *UISetVarRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/native.NativeService/UISetVar", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) UIGetVar(ctx context.Context, in *UIGetVarRequest, opts ...grpc.CallOption) (*UIGetVarResponse, error) {
	out := new(UIGetVarResponse)
	err := c.cc.Invoke(ctx, "/native.NativeService/UIGetVar", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) UIObjAddState(ctx context.Context, in *UIObjAddStateRequest, opts ...grpc.CallOption) (*UIObjAddStateResponse, error) {
	out := new(UIObjAddStateResponse)
	err := c.cc.Invoke(ctx, "/native.NativeService/UIObjAddState", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) UIObjClearState(ctx context.Context, in *UIObjClearStateRequest, opts ...grpc.CallOption) (*UIObjClearStateResponse, error) {
	out := new(UIObjClearStateResponse)
	err := c.cc.Invoke(ctx, "/native.NativeService/UIObjClearState", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) UIObjAddFlag(ctx context.Context, in *UIObjAddFlagRequest, opts ...grpc.CallOption) (*UIObjAddFlagResponse, error) {
	out := new(UIObjAddFlagResponse)
	err := c.cc.Invoke(ctx, "/native.NativeService/UIObjAddFlag", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) UIObjClearFlag(ctx context.Context, in *UIObjClearFlagRequest, opts ...grpc.CallOption) (*UIObjClearFlagResponse, error) {
	out := new(UIObjClearFlagResponse)
	err := c.cc.Invoke(ctx, "/native.NativeService/UIObjClearFlag", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) UIObjSetOpacity(ctx context.Context, in *UIObjSetOpacityRequest, opts ...grpc.CallOption) (*UIObjSetOpacityResponse, error) {
	out := new(UIObjSetOpacityResponse)
	err := c.cc.Invoke(ctx, "/native.NativeService/UIObjSetOpacity", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) UIObjFadeIn(ctx context.Context, in *UIObjFadeInRequest, opts ...grpc.CallOption) (*UIObjFadeInResponse, error) {
	out := new(UIObjFadeInResponse)
	err := c.cc.Invoke(ctx, "/native.NativeService/UIObjFadeIn", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) UIObjFadeOut(ctx context.Context, in *UIObjFadeOutRequest, opts ...grpc.CallOption) (*UIObjFadeOutResponse, error) {
	out := new(UIObjFadeOutResponse)
	err := c.cc.Invoke(ctx, "/native.NativeService/UIObjFadeOut", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) UIObjSetLabelText(ctx context.Context, in *UIObjSetLabelTextRequest, opts ...grpc.CallOption) (*UIObjSetLabelTextResponse, error) {
	out := new(UIObjSetLabelTextResponse)
	err := c.cc.Invoke(ctx, "/native.NativeService/UIObjSetLabelText", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) UIObjSetImageSrc(ctx context.Context, in *UIObjSetImageSrcRequest, opts ...grpc.CallOption) (*UIObjSetImageSrcResponse, error) {
	out := new(UIObjSetImageSrcResponse)
	err := c.cc.Invoke(ctx, "/native.NativeService/UIObjSetImageSrc", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) DisplaySetRotation(ctx context.Context, in *DisplaySetRotationRequest, opts ...grpc.CallOption) (*DisplaySetRotationResponse, error) {
	out := new(DisplaySetRotationResponse)
	err := c.cc.Invoke(ctx, "/native.NativeService/DisplaySetRotation", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) UpdateLabelIfChanged(ctx context.Context, in *UpdateLabelIfChangedRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/native.NativeService/UpdateLabelIfChanged", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) UpdateLabelAndChangeVisibility(ctx context.Context, in *UpdateLabelAndChangeVisibilityRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/native.NativeService/UpdateLabelAndChangeVisibility", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) SwitchToScreenIf(ctx context.Context, in *SwitchToScreenIfRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/native.NativeService/SwitchToScreenIf", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) SwitchToScreenIfDifferent(ctx context.Context, in *SwitchToScreenIfDifferentRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/native.NativeService/SwitchToScreenIfDifferent", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) DoNotUseThisIsForCrashTestingOnly(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/native.NativeService/DoNotUseThisIsForCrashTestingOnly", in, out, opts...)
	return out, err
}

func (c *nativeServiceClient) StreamEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (NativeService_StreamEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &NativeService_ServiceDesc.Streams[0], "/native.NativeService/StreamEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &nativeServiceStreamEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NativeService_StreamEventsClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type nativeServiceStreamEventsClient struct {
	grpc.ClientStream
}

func (x *nativeServiceStreamEventsClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NativeServiceServer is the server API for NativeService service.
type NativeServiceServer interface {
	// Video methods
	VideoSetSleepMode(context.Context, *VideoSetSleepModeRequest) (*Empty, error)
	VideoGetSleepMode(context.Context, *Empty) (*VideoGetSleepModeResponse, error)
	VideoSleepModeSupported(context.Context, *Empty) (*VideoSleepModeSupportedResponse, error)
	VideoSetQualityFactor(context.Context, *VideoSetQualityFactorRequest) (*Empty, error)
	VideoGetQualityFactor(context.Context, *Empty) (*VideoGetQualityFactorResponse, error)
	VideoSetEDID(context.Context, *VideoSetEDIDRequest) (*Empty, error)
	VideoGetEDID(context.Context, *Empty) (*VideoGetEDIDResponse, error)
	VideoLogStatus(context.Context, *Empty) (*VideoLogStatusResponse, error)
	VideoStop(context.Context, *Empty) (*Empty, error)
	VideoStart(context.Context, *Empty) (*Empty, error)
	// UI methods
	GetLVGLVersion(context.Context, *Empty) (*GetLVGLVersionResponse, error)
	UIObjHide(context.Context, *UIObjHideRequest) (*UIObjHideResponse, error)
	UIObjShow(context.Context, *UIObjShowRequest) (*UIObjShowResponse, error)
	UISetVar(context.Context, *UISetVarRequest) (*Empty, error)
	UIGetVar(context.Context, *UIGetVarRequest) (*UIGetVarResponse, error)
	UIObjAddState(context.Context, *UIObjAddStateRequest) (*UIObjAddStateResponse, error)
	UIObjClearState(context.Context, *UIObjClearStateRequest) (*UIObjClearStateResponse, error)
	UIObjAddFlag(context.Context, *UIObjAddFlagRequest) (*UIObjAddFlagResponse, error)
	UIObjClearFlag(context.Context, *UIObjClearFlagRequest) (*UIObjClearFlagResponse, error)
	UIObjSetOpacity(context.Context, *UIObjSetOpacityRequest) (*UIObjSetOpacityResponse, error)
	UIObjFadeIn(context.Context, *UIObjFadeInRequest) (*UIObjFadeInResponse, error)
	UIObjFadeOut(context.Context, *UIObjFadeOutRequest) (*UIObjFadeOutResponse, error)
	UIObjSetLabelText(context.Context, *UIObjSetLabelTextRequest) (*UIObjSetLabelTextResponse, error)
	UIObjSetImageSrc(context.Context, *UIObjSetImageSrcRequest) (*UIObjSetImageSrcResponse, error)
	DisplaySetRotation(context.Context, *DisplaySetRotationRequest) (*DisplaySetRotationResponse, error)
	UpdateLabelIfChanged(context.Context, *UpdateLabelIfChangedRequest) (*Empty, error)
	UpdateLabelAndChangeVisibility(context.Context, *UpdateLabelAndChangeVisibilityRequest) (*Empty, error)
	SwitchToScreenIf(context.Context, *SwitchToScreenIfRequest) (*Empty, error)
	SwitchToScreenIfDifferent(context.Context, *SwitchToScreenIfDifferentRequest) (*Empty, error)
	// Testing
	DoNotUseThisIsForCrashTestingOnly(context.Context, *Empty) (*Empty, error)
	// Events stream
	StreamEvents(*Empty, NativeService_StreamEventsServer) error
	mustEmbedUnimplementedNativeServiceServer()
}

// UnimplementedNativeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNativeServiceServer struct {
}

func (UnimplementedNativeServiceServer) VideoSetSleepMode(context.Context, *VideoSetSleepModeRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VideoSetSleepMode not implemented")
}

func (UnimplementedNativeServiceServer) VideoGetSleepMode(context.Context, *Empty) (*VideoGetSleepModeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VideoGetSleepMode not implemented")
}

func (UnimplementedNativeServiceServer) VideoSleepModeSupported(context.Context, *Empty) (*VideoSleepModeSupportedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VideoSleepModeSupported not implemented")
}

func (UnimplementedNativeServiceServer) VideoSetQualityFactor(context.Context, *VideoSetQualityFactorRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VideoSetQualityFactor not implemented")
}

func (UnimplementedNativeServiceServer) VideoGetQualityFactor(context.Context, *Empty) (*VideoGetQualityFactorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VideoGetQualityFactor not implemented")
}

func (UnimplementedNativeServiceServer) VideoSetEDID(context.Context, *VideoSetEDIDRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VideoSetEDID not implemented")
}

func (UnimplementedNativeServiceServer) VideoGetEDID(context.Context, *Empty) (*VideoGetEDIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VideoGetEDID not implemented")
}

func (UnimplementedNativeServiceServer) VideoLogStatus(context.Context, *Empty) (*VideoLogStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VideoLogStatus not implemented")
}

func (UnimplementedNativeServiceServer) VideoStop(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VideoStop not implemented")
}

func (UnimplementedNativeServiceServer) VideoStart(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VideoStart not implemented")
}

func (UnimplementedNativeServiceServer) GetLVGLVersion(context.Context, *Empty) (*GetLVGLVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLVGLVersion not implemented")
}

func (UnimplementedNativeServiceServer) UIObjHide(context.Context, *UIObjHideRequest) (*UIObjHideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UIObjHide not implemented")
}

func (UnimplementedNativeServiceServer) UIObjShow(context.Context, *UIObjShowRequest) (*UIObjShowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UIObjShow not implemented")
}

func (UnimplementedNativeServiceServer) UISetVar(context.Context, *UISetVarRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UISetVar not implemented")
}

func (UnimplementedNativeServiceServer) UIGetVar(context.Context, *UIGetVarRequest) (*UIGetVarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UIGetVar not implemented")
}

func (UnimplementedNativeServiceServer) UIObjAddState(context.Context, *UIObjAddStateRequest) (*UIObjAddStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UIObjAddState not implemented")
}

func (UnimplementedNativeServiceServer) UIObjClearState(context.Context, *UIObjClearStateRequest) (*UIObjClearStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UIObjClearState not implemented")
}

func (UnimplementedNativeServiceServer) UIObjAddFlag(context.Context, *UIObjAddFlagRequest) (*UIObjAddFlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UIObjAddFlag not implemented")
}

func (UnimplementedNativeServiceServer) UIObjClearFlag(context.Context, *UIObjClearFlagRequest) (*UIObjClearFlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UIObjClearFlag not implemented")
}

func (UnimplementedNativeServiceServer) UIObjSetOpacity(context.Context, *UIObjSetOpacityRequest) (*UIObjSetOpacityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UIObjSetOpacity not implemented")
}

func (UnimplementedNativeServiceServer) UIObjFadeIn(context.Context, *UIObjFadeInRequest) (*UIObjFadeInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UIObjFadeIn not implemented")
}

func (UnimplementedNativeServiceServer) UIObjFadeOut(context.Context, *UIObjFadeOutRequest) (*UIObjFadeOutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UIObjFadeOut not implemented")
}

func (UnimplementedNativeServiceServer) UIObjSetLabelText(context.Context, *UIObjSetLabelTextRequest) (*UIObjSetLabelTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UIObjSetLabelText not implemented")
}

func (UnimplementedNativeServiceServer) UIObjSetImageSrc(context.Context, *UIObjSetImageSrcRequest) (*UIObjSetImageSrcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UIObjSetImageSrc not implemented")
}

func (UnimplementedNativeServiceServer) DisplaySetRotation(context.Context, *DisplaySetRotationRequest) (*DisplaySetRotationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisplaySetRotation not implemented")
}

func (UnimplementedNativeServiceServer) UpdateLabelIfChanged(context.Context, *UpdateLabelIfChangedRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLabelIfChanged not implemented")
}

func (UnimplementedNativeServiceServer) UpdateLabelAndChangeVisibility(context.Context, *UpdateLabelAndChangeVisibilityRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLabelAndChangeVisibility not implemented")
}

func (UnimplementedNativeServiceServer) SwitchToScreenIf(context.Context, *SwitchToScreenIfRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwitchToScreenIf not implemented")
}

func (UnimplementedNativeServiceServer) SwitchToScreenIfDifferent(context.Context, *SwitchToScreenIfDifferentRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwitchToScreenIfDifferent not implemented")
}

func (UnimplementedNativeServiceServer) DoNotUseThisIsForCrashTestingOnly(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoNotUseThisIsForCrashTestingOnly not implemented")
}

func (UnimplementedNativeServiceServer) StreamEvents(*Empty, NativeService_StreamEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}

func (UnimplementedNativeServiceServer) mustEmbedUnimplementedNativeServiceServer() {}

// UnsafeNativeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NativeServiceServer will
// result in compilation errors.
type UnsafeNativeServiceServer interface {
	mustEmbedUnimplementedNativeServiceServer()
}

func RegisterNativeServiceServer(s grpc.ServiceRegistrar, srv NativeServiceServer) {
	s.RegisterService(&NativeService_ServiceDesc, srv)
}

type NativeService_StreamEventsServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type nativeServiceStreamEventsServer struct {
	grpc.ServerStream
}

func (x *nativeServiceStreamEventsServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

// NativeService_ServiceDesc is the grpc.ServiceDesc for NativeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NativeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "native.NativeService",
	HandlerType: (*NativeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VideoSetSleepMode",
			Handler:    nil, // Will be set by RegisterNativeServiceServer
		},
		// Additional methods will be registered here
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       nil, // Will be set by RegisterNativeServiceServer
			ServerStreams: true,
		},
	},
	Metadata: "native.proto",
}
