// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/native/proto/native.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_native_proto_native_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{0}
}

type IsReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsReadyRequest) Reset() {
	*x = IsReadyRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsReadyRequest) ProtoMessage() {}

func (x *IsReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsReadyRequest.ProtoReflect.Descriptor instead.
func (*IsReadyRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{1}
}

type IsReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	VideoReady    bool                   `protobuf:"varint,3,opt,name=video_ready,json=videoReady,proto3" json:"video_ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsReadyResponse) Reset() {
	*x = IsReadyResponse{}
	mi := &file_internal_native_proto_native_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsReadyResponse) ProtoMessage() {}

func (x *IsReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsReadyResponse.ProtoReflect.Descriptor instead.
func (*IsReadyResponse) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{2}
}

func (x *IsReadyResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *IsReadyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *IsReadyResponse) GetVideoReady() bool {
	if x != nil {
		return x.VideoReady
	}
	return false
}

type VideoState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ready          bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Error          string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Width          int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height         int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	FramePerSecond float64                `protobuf:"fixed64,5,opt,name=frame_per_second,json=framePerSecond,proto3" json:"frame_per_second,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VideoState) Reset() {
	*x = VideoState{}
	mi := &file_internal_native_proto_native_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoState) ProtoMessage() {}

func (x *VideoState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoState.ProtoReflect.Descriptor instead.
func (*VideoState) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{3}
}

func (x *VideoState) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *VideoState) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *VideoState) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VideoState) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VideoState) GetFramePerSecond() float64 {
	if x != nil {
		return x.FramePerSecond
	}
	return 0
}

type VideoSetSleepModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoSetSleepModeRequest) Reset() {
	*x = VideoSetSleepModeRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoSetSleepModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoSetSleepModeRequest) ProtoMessage() {}

func (x *VideoSetSleepModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoSetSleepModeRequest.ProtoReflect.Descriptor instead.
func (*VideoSetSleepModeRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{4}
}

func (x *VideoSetSleepModeRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type VideoGetSleepModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoGetSleepModeResponse) Reset() {
	*x = VideoGetSleepModeResponse{}
	mi := &file_internal_native_proto_native_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoGetSleepModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoGetSleepModeResponse) ProtoMessage() {}

func (x *VideoGetSleepModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoGetSleepModeResponse.ProtoReflect.Descriptor instead.
func (*VideoGetSleepModeResponse) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{5}
}

func (x *VideoGetSleepModeResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type VideoSleepModeSupportedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Supported     bool                   `protobuf:"varint,1,opt,name=supported,proto3" json:"supported,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoSleepModeSupportedResponse) Reset() {
	*x = VideoSleepModeSupportedResponse{}
	mi := &file_internal_native_proto_native_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoSleepModeSupportedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoSleepModeSupportedResponse) ProtoMessage() {}

func (x *VideoSleepModeSupportedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoSleepModeSupportedResponse.ProtoReflect.Descriptor instead.
func (*VideoSleepModeSupportedResponse) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{6}
}

func (x *VideoSleepModeSupportedResponse) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

type VideoSetQualityFactorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Factor        float64                `protobuf:"fixed64,1,opt,name=factor,proto3" json:"factor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoSetQualityFactorRequest) Reset() {
	*x = VideoSetQualityFactorRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoSetQualityFactorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoSetQualityFactorRequest) ProtoMessage() {}

func (x *VideoSetQualityFactorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoSetQualityFactorRequest.ProtoReflect.Descriptor instead.
func (*VideoSetQualityFactorRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{7}
}

func (x *VideoSetQualityFactorRequest) GetFactor() float64 {
	if x != nil {
		return x.Factor
	}
	return 0
}

type VideoGetQualityFactorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Factor        float64                `protobuf:"fixed64,1,opt,name=factor,proto3" json:"factor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoGetQualityFactorResponse) Reset() {
	*x = VideoGetQualityFactorResponse{}
	mi := &file_internal_native_proto_native_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoGetQualityFactorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoGetQualityFactorResponse) ProtoMessage() {}

func (x *VideoGetQualityFactorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoGetQualityFactorResponse.ProtoReflect.Descriptor instead.
func (*VideoGetQualityFactorResponse) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{8}
}

func (x *VideoGetQualityFactorResponse) GetFactor() float64 {
	if x != nil {
		return x.Factor
	}
	return 0
}

type VideoSetCodecTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CodecType     int32                  `protobuf:"varint,1,opt,name=codec_type,json=codecType,proto3" json:"codec_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoSetCodecTypeRequest) Reset() {
	*x = VideoSetCodecTypeRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoSetCodecTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoSetCodecTypeRequest) ProtoMessage() {}

func (x *VideoSetCodecTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoSetCodecTypeRequest.ProtoReflect.Descriptor instead.
func (*VideoSetCodecTypeRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{9}
}

func (x *VideoSetCodecTypeRequest) GetCodecType() int32 {
	if x != nil {
		return x.CodecType
	}
	return 0
}

type VideoGetCodecTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CodecType     int32                  `protobuf:"varint,1,opt,name=codec_type,json=codecType,proto3" json:"codec_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoGetCodecTypeResponse) Reset() {
	*x = VideoGetCodecTypeResponse{}
	mi := &file_internal_native_proto_native_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoGetCodecTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoGetCodecTypeResponse) ProtoMessage() {}

func (x *VideoGetCodecTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoGetCodecTypeResponse.ProtoReflect.Descriptor instead.
func (*VideoGetCodecTypeResponse) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{10}
}

func (x *VideoGetCodecTypeResponse) GetCodecType() int32 {
	if x != nil {
		return x.CodecType
	}
	return 0
}

type VideoSetEDIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edid          string                 `protobuf:"bytes,1,opt,name=edid,proto3" json:"edid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoSetEDIDRequest) Reset() {
	*x = VideoSetEDIDRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoSetEDIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoSetEDIDRequest) ProtoMessage() {}

func (x *VideoSetEDIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoSetEDIDRequest.ProtoReflect.Descriptor instead.
func (*VideoSetEDIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{11}
}

func (x *VideoSetEDIDRequest) GetEdid() string {
	if x != nil {
		return x.Edid
	}
	return ""
}

type VideoGetEDIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edid          string                 `protobuf:"bytes,1,opt,name=edid,proto3" json:"edid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoGetEDIDResponse) Reset() {
	*x = VideoGetEDIDResponse{}
	mi := &file_internal_native_proto_native_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoGetEDIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoGetEDIDResponse) ProtoMessage() {}

func (x *VideoGetEDIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoGetEDIDResponse.ProtoReflect.Descriptor instead.
func (*VideoGetEDIDResponse) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{12}
}

func (x *VideoGetEDIDResponse) GetEdid() string {
	if x != nil {
		return x.Edid
	}
	return ""
}

type VideoLogStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoLogStatusResponse) Reset() {
	*x = VideoLogStatusResponse{}
	mi := &file_internal_native_proto_native_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoLogStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoLogStatusResponse) ProtoMessage() {}

func (x *VideoLogStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoLogStatusResponse.ProtoReflect.Descriptor instead.
func (*VideoLogStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{13}
}

func (x *VideoLogStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetLVGLVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLVGLVersionResponse) Reset() {
	*x = GetLVGLVersionResponse{}
	mi := &file_internal_native_proto_native_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLVGLVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLVGLVersionResponse) ProtoMessage() {}

func (x *GetLVGLVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLVGLVersionResponse.ProtoReflect.Descriptor instead.
func (*GetLVGLVersionResponse) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{14}
}

func (x *GetLVGLVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type UIObjHideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjName       string                 `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjHideRequest) Reset() {
	*x = UIObjHideRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjHideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjHideRequest) ProtoMessage() {}

func (x *UIObjHideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjHideRequest.ProtoReflect.Descriptor instead.
func (*UIObjHideRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{15}
}

func (x *UIObjHideRequest) GetObjName() string {
	if x != nil {
		return x.ObjName
	}
	return ""
}

type UIObjHideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjHideResponse) Reset() {
	*x = UIObjHideResponse{}
	mi := &file_internal_native_proto_native_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjHideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjHideResponse) ProtoMessage() {}

func (x *UIObjHideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjHideResponse.ProtoReflect.Descriptor instead.
func (*UIObjHideResponse) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{16}
}

func (x *UIObjHideResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UIObjShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjName       string                 `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjShowRequest) Reset() {
	*x = UIObjShowRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjShowRequest) ProtoMessage() {}

func (x *UIObjShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjShowRequest.ProtoReflect.Descriptor instead.
func (*UIObjShowRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{17}
}

func (x *UIObjShowRequest) GetObjName() string {
	if x != nil {
		return x.ObjName
	}
	return ""
}

type UIObjShowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjShowResponse) Reset() {
	*x = UIObjShowResponse{}
	mi := &file_internal_native_proto_native_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjShowResponse) ProtoMessage() {}

func (x *UIObjShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjShowResponse.ProtoReflect.Descriptor instead.
func (*UIObjShowResponse) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{18}
}

func (x *UIObjShowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UISetVarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UISetVarRequest) Reset() {
	*x = UISetVarRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UISetVarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UISetVarRequest) ProtoMessage() {}

func (x *UISetVarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UISetVarRequest.ProtoReflect.Descriptor instead.
func (*UISetVarRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{19}
}

func (x *UISetVarRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UISetVarRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UIGetVarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIGetVarRequest) Reset() {
	*x = UIGetVarRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIGetVarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIGetVarRequest) ProtoMessage() {}

func (x *UIGetVarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIGetVarRequest.ProtoReflect.Descriptor instead.
func (*UIGetVarRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{20}
}

func (x *UIGetVarRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UIGetVarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIGetVarResponse) Reset() {
	*x = UIGetVarResponse{}
	mi := &file_internal_native_proto_native_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIGetVarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIGetVarResponse) ProtoMessage() {}

func (x *UIGetVarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIGetVarResponse.ProtoReflect.Descriptor instead.
func (*UIGetVarResponse) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{21}
}

func (x *UIGetVarResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UIObjAddStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjName       string                 `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjAddStateRequest) Reset() {
	*x = UIObjAddStateRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjAddStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjAddStateRequest) ProtoMessage() {}

func (x *UIObjAddStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjAddStateRequest.ProtoReflect.Descriptor instead.
func (*UIObjAddStateRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{22}
}

func (x *UIObjAddStateRequest) GetObjName() string {
	if x != nil {
		return x.ObjName
	}
	return ""
}

func (x *UIObjAddStateRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type UIObjAddStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjAddStateResponse) Reset() {
	*x = UIObjAddStateResponse{}
	mi := &file_internal_native_proto_native_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjAddStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjAddStateResponse) ProtoMessage() {}

func (x *UIObjAddStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjAddStateResponse.ProtoReflect.Descriptor instead.
func (*UIObjAddStateResponse) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{23}
}

func (x *UIObjAddStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UIObjClearStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjName       string                 `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjClearStateRequest) Reset() {
	*x = UIObjClearStateRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjClearStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjClearStateRequest) ProtoMessage() {}

func (x *UIObjClearStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjClearStateRequest.ProtoReflect.Descriptor instead.
func (*UIObjClearStateRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{24}
}

func (x *UIObjClearStateRequest) GetObjName() string {
	if x != nil {
		return x.ObjName
	}
	return ""
}

func (x *UIObjClearStateRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type UIObjClearStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjClearStateResponse) Reset() {
	*x = UIObjClearStateResponse{}
	mi := &file_internal_native_proto_native_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjClearStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjClearStateResponse) ProtoMessage() {}

func (x *UIObjClearStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjClearStateResponse.ProtoReflect.Descriptor instead.
func (*UIObjClearStateResponse) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{25}
}

func (x *UIObjClearStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UIObjAddFlagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjName       string                 `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	Flag          string                 `protobuf:"bytes,2,opt,name=flag,proto3" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjAddFlagRequest) Reset() {
	*x = UIObjAddFlagRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjAddFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjAddFlagRequest) ProtoMessage() {}

func (x *UIObjAddFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjAddFlagRequest.ProtoReflect.Descriptor instead.
func (*UIObjAddFlagRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{26}
}

func (x *UIObjAddFlagRequest) GetObjName() string {
	if x != nil {
		return x.ObjName
	}
	return ""
}

func (x *UIObjAddFlagRequest) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

type UIObjAddFlagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjAddFlagResponse) Reset() {
	*x = UIObjAddFlagResponse{}
	mi := &file_internal_native_proto_native_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjAddFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjAddFlagResponse) ProtoMessage() {}

func (x *UIObjAddFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjAddFlagResponse.ProtoReflect.Descriptor instead.
func (*UIObjAddFlagResponse) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{27}
}

func (x *UIObjAddFlagResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UIObjClearFlagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjName       string                 `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	Flag          string                 `protobuf:"bytes,2,opt,name=flag,proto3" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjClearFlagRequest) Reset() {
	*x = UIObjClearFlagRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjClearFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjClearFlagRequest) ProtoMessage() {}

func (x *UIObjClearFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjClearFlagRequest.ProtoReflect.Descriptor instead.
func (*UIObjClearFlagRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{28}
}

func (x *UIObjClearFlagRequest) GetObjName() string {
	if x != nil {
		return x.ObjName
	}
	return ""
}

func (x *UIObjClearFlagRequest) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

type UIObjClearFlagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjClearFlagResponse) Reset() {
	*x = UIObjClearFlagResponse{}
	mi := &file_internal_native_proto_native_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjClearFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjClearFlagResponse) ProtoMessage() {}

func (x *UIObjClearFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjClearFlagResponse.ProtoReflect.Descriptor instead.
func (*UIObjClearFlagResponse) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{29}
}

func (x *UIObjClearFlagResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UIObjSetOpacityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjName       string                 `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	Opacity       int32                  `protobuf:"varint,2,opt,name=opacity,proto3" json:"opacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjSetOpacityRequest) Reset() {
	*x = UIObjSetOpacityRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjSetOpacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjSetOpacityRequest) ProtoMessage() {}

func (x *UIObjSetOpacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjSetOpacityRequest.ProtoReflect.Descriptor instead.
func (*UIObjSetOpacityRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{30}
}

func (x *UIObjSetOpacityRequest) GetObjName() string {
	if x != nil {
		return x.ObjName
	}
	return ""
}

func (x *UIObjSetOpacityRequest) GetOpacity() int32 {
	if x != nil {
		return x.Opacity
	}
	return 0
}

type UIObjSetOpacityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjSetOpacityResponse) Reset() {
	*x = UIObjSetOpacityResponse{}
	mi := &file_internal_native_proto_native_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjSetOpacityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjSetOpacityResponse) ProtoMessage() {}

func (x *UIObjSetOpacityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjSetOpacityResponse.ProtoReflect.Descriptor instead.
func (*UIObjSetOpacityResponse) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{31}
}

func (x *UIObjSetOpacityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UIObjFadeInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjName       string                 `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	Duration      uint32                 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjFadeInRequest) Reset() {
	*x = UIObjFadeInRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjFadeInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjFadeInRequest) ProtoMessage() {}

func (x *UIObjFadeInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjFadeInRequest.ProtoReflect.Descriptor instead.
func (*UIObjFadeInRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{32}
}

func (x *UIObjFadeInRequest) GetObjName() string {
	if x != nil {
		return x.ObjName
	}
	return ""
}

func (x *UIObjFadeInRequest) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type UIObjFadeInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjFadeInResponse) Reset() {
	*x = UIObjFadeInResponse{}
	mi := &file_internal_native_proto_native_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjFadeInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjFadeInResponse) ProtoMessage() {}

func (x *UIObjFadeInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjFadeInResponse.ProtoReflect.Descriptor instead.
func (*UIObjFadeInResponse) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{33}
}

func (x *UIObjFadeInResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UIObjFadeOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjName       string                 `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	Duration      uint32                 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjFadeOutRequest) Reset() {
	*x = UIObjFadeOutRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjFadeOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjFadeOutRequest) ProtoMessage() {}

func (x *UIObjFadeOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjFadeOutRequest.ProtoReflect.Descriptor instead.
func (*UIObjFadeOutRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{34}
}

func (x *UIObjFadeOutRequest) GetObjName() string {
	if x != nil {
		return x.ObjName
	}
	return ""
}

func (x *UIObjFadeOutRequest) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type UIObjFadeOutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjFadeOutResponse) Reset() {
	*x = UIObjFadeOutResponse{}
	mi := &file_internal_native_proto_native_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjFadeOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjFadeOutResponse) ProtoMessage() {}

func (x *UIObjFadeOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjFadeOutResponse.ProtoReflect.Descriptor instead.
func (*UIObjFadeOutResponse) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{35}
}

func (x *UIObjFadeOutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UIObjSetLabelTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjName       string                 `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjSetLabelTextRequest) Reset() {
	*x = UIObjSetLabelTextRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjSetLabelTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjSetLabelTextRequest) ProtoMessage() {}

func (x *UIObjSetLabelTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjSetLabelTextRequest.ProtoReflect.Descriptor instead.
func (*UIObjSetLabelTextRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{36}
}

func (x *UIObjSetLabelTextRequest) GetObjName() string {
	if x != nil {
		return x.ObjName
	}
	return ""
}

func (x *UIObjSetLabelTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type UIObjSetLabelTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjSetLabelTextResponse) Reset() {
	*x = UIObjSetLabelTextResponse{}
	mi := &file_internal_native_proto_native_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjSetLabelTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjSetLabelTextResponse) ProtoMessage() {}

func (x *UIObjSetLabelTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjSetLabelTextResponse.ProtoReflect.Descriptor instead.
func (*UIObjSetLabelTextResponse) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{37}
}

func (x *UIObjSetLabelTextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UIObjSetImageSrcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjName       string                 `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjSetImageSrcRequest) Reset() {
	*x = UIObjSetImageSrcRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjSetImageSrcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjSetImageSrcRequest) ProtoMessage() {}

func (x *UIObjSetImageSrcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjSetImageSrcRequest.ProtoReflect.Descriptor instead.
func (*UIObjSetImageSrcRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{38}
}

func (x *UIObjSetImageSrcRequest) GetObjName() string {
	if x != nil {
		return x.ObjName
	}
	return ""
}

func (x *UIObjSetImageSrcRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type UIObjSetImageSrcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIObjSetImageSrcResponse) Reset() {
	*x = UIObjSetImageSrcResponse{}
	mi := &file_internal_native_proto_native_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIObjSetImageSrcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIObjSetImageSrcResponse) ProtoMessage() {}

func (x *UIObjSetImageSrcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIObjSetImageSrcResponse.ProtoReflect.Descriptor instead.
func (*UIObjSetImageSrcResponse) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{39}
}

func (x *UIObjSetImageSrcResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DisplaySetRotationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rotation      uint32                 `protobuf:"varint,1,opt,name=rotation,proto3" json:"rotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisplaySetRotationRequest) Reset() {
	*x = DisplaySetRotationRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplaySetRotationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplaySetRotationRequest) ProtoMessage() {}

func (x *DisplaySetRotationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplaySetRotationRequest.ProtoReflect.Descriptor instead.
func (*DisplaySetRotationRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{40}
}

func (x *DisplaySetRotationRequest) GetRotation() uint32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

type DisplaySetRotationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisplaySetRotationResponse) Reset() {
	*x = DisplaySetRotationResponse{}
	mi := &file_internal_native_proto_native_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplaySetRotationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplaySetRotationResponse) ProtoMessage() {}

func (x *DisplaySetRotationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplaySetRotationResponse.ProtoReflect.Descriptor instead.
func (*DisplaySetRotationResponse) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{41}
}

func (x *DisplaySetRotationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateLabelIfChangedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjName       string                 `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	NewText       string                 `protobuf:"bytes,2,opt,name=new_text,json=newText,proto3" json:"new_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLabelIfChangedRequest) Reset() {
	*x = UpdateLabelIfChangedRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLabelIfChangedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLabelIfChangedRequest) ProtoMessage() {}

func (x *UpdateLabelIfChangedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLabelIfChangedRequest.ProtoReflect.Descriptor instead.
func (*UpdateLabelIfChangedRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{42}
}

func (x *UpdateLabelIfChangedRequest) GetObjName() string {
	if x != nil {
		return x.ObjName
	}
	return ""
}

func (x *UpdateLabelIfChangedRequest) GetNewText() string {
	if x != nil {
		return x.NewText
	}
	return ""
}

type UpdateLabelAndChangeVisibilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjName       string                 `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	NewText       string                 `protobuf:"bytes,2,opt,name=new_text,json=newText,proto3" json:"new_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLabelAndChangeVisibilityRequest) Reset() {
	*x = UpdateLabelAndChangeVisibilityRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLabelAndChangeVisibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLabelAndChangeVisibilityRequest) ProtoMessage() {}

func (x *UpdateLabelAndChangeVisibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLabelAndChangeVisibilityRequest.ProtoReflect.Descriptor instead.
func (*UpdateLabelAndChangeVisibilityRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{43}
}

func (x *UpdateLabelAndChangeVisibilityRequest) GetObjName() string {
	if x != nil {
		return x.ObjName
	}
	return ""
}

func (x *UpdateLabelAndChangeVisibilityRequest) GetNewText() string {
	if x != nil {
		return x.NewText
	}
	return ""
}

type SwitchToScreenIfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScreenName    string                 `protobuf:"bytes,1,opt,name=screen_name,json=screenName,proto3" json:"screen_name,omitempty"`
	ShouldSwitch  []string               `protobuf:"bytes,2,rep,name=should_switch,json=shouldSwitch,proto3" json:"should_switch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchToScreenIfRequest) Reset() {
	*x = SwitchToScreenIfRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchToScreenIfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchToScreenIfRequest) ProtoMessage() {}

func (x *SwitchToScreenIfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchToScreenIfRequest.ProtoReflect.Descriptor instead.
func (*SwitchToScreenIfRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{44}
}

func (x *SwitchToScreenIfRequest) GetScreenName() string {
	if x != nil {
		return x.ScreenName
	}
	return ""
}

func (x *SwitchToScreenIfRequest) GetShouldSwitch() []string {
	if x != nil {
		return x.ShouldSwitch
	}
	return nil
}

type SwitchToScreenIfDifferentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScreenName    string                 `protobuf:"bytes,1,opt,name=screen_name,json=screenName,proto3" json:"screen_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchToScreenIfDifferentRequest) Reset() {
	*x = SwitchToScreenIfDifferentRequest{}
	mi := &file_internal_native_proto_native_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchToScreenIfDifferentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchToScreenIfDifferentRequest) ProtoMessage() {}

func (x *SwitchToScreenIfDifferentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchToScreenIfDifferentRequest.ProtoReflect.Descriptor instead.
func (*SwitchToScreenIfDifferentRequest) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{45}
}

func (x *SwitchToScreenIfDifferentRequest) GetScreenName() string {
	if x != nil {
		return x.ScreenName
	}
	return ""
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*Event_VideoState
	//	*Event_IndevEvent
	//	*Event_RpcEvent
	//	*Event_VideoFrame
	Data          isEvent_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_internal_native_proto_native_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{46}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetData() isEvent_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Event) GetVideoState() *VideoState {
	if x != nil {
		if x, ok := x.Data.(*Event_VideoState); ok {
			return x.VideoState
		}
	}
	return nil
}

func (x *Event) GetIndevEvent() string {
	if x != nil {
		if x, ok := x.Data.(*Event_IndevEvent); ok {
			return x.IndevEvent
		}
	}
	return ""
}

func (x *Event) GetRpcEvent() string {
	if x != nil {
		if x, ok := x.Data.(*Event_RpcEvent); ok {
			return x.RpcEvent
		}
	}
	return ""
}

func (x *Event) GetVideoFrame() *VideoFrame {
	if x != nil {
		if x, ok := x.Data.(*Event_VideoFrame); ok {
			return x.VideoFrame
		}
	}
	return nil
}

type isEvent_Data interface {
	isEvent_Data()
}

type Event_VideoState struct {
	VideoState *VideoState `protobuf:"bytes,2,opt,name=video_state,json=videoState,proto3,oneof"`
}

type Event_IndevEvent struct {
	IndevEvent string `protobuf:"bytes,3,opt,name=indev_event,json=indevEvent,proto3,oneof"`
}

type Event_RpcEvent struct {
	RpcEvent string `protobuf:"bytes,4,opt,name=rpc_event,json=rpcEvent,proto3,oneof"`
}

type Event_VideoFrame struct {
	VideoFrame *VideoFrame `protobuf:"bytes,5,opt,name=video_frame,json=videoFrame,proto3,oneof"`
}

func (*Event_VideoState) isEvent_Data() {}

func (*Event_IndevEvent) isEvent_Data() {}

func (*Event_RpcEvent) isEvent_Data() {}

func (*Event_VideoFrame) isEvent_Data() {}

type VideoFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frame         []byte                 `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"`
	DurationNs    int64                  `protobuf:"varint,2,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoFrame) Reset() {
	*x = VideoFrame{}
	mi := &file_internal_native_proto_native_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoFrame) ProtoMessage() {}

func (x *VideoFrame) ProtoReflect() protoreflect.Message {
	mi := &file_internal_native_proto_native_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoFrame.ProtoReflect.Descriptor instead.
func (*VideoFrame) Descriptor() ([]byte, []int) {
	return file_internal_native_proto_native_proto_rawDescGZIP(), []int{47}
}

func (x *VideoFrame) GetFrame() []byte {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *VideoFrame) GetDurationNs() int64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

var File_internal_native_proto_native_proto protoreflect.FileDescriptor

const file_internal_native_proto_native_proto_rawDesc = "" +
	"\n" +
	"\"internal/native/proto/native.proto\x12\x06native\"\a\n" +
	"\x05Empty\"\x10\n" +
	"\x0eIsReadyRequest\"^\n" +
	"\x0fIsReadyResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vvideo_ready\x18\x03 \x01(\bR\n" +
	"videoReady\"\x90\x01\n" +
	"\n" +
	"VideoState\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12(\n" +
	"\x10frame_per_second\x18\x05 \x01(\x01R\x0eframePerSecond\"4\n" +
	"\x18VideoSetSleepModeRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"5\n" +
	"\x19VideoGetSleepModeResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"?\n" +
	"\x1fVideoSleepModeSupportedResponse\x12\x1c\n" +
	"\tsupported\x18\x01 \x01(\bR\tsupported\"6\n" +
	"\x1cVideoSetQualityFactorRequest\x12\x16\n" +
	"\x06factor\x18\x01 \x01(\x01R\x06factor\"7\n" +
	"\x1dVideoGetQualityFactorResponse\x12\x16\n" +
	"\x06factor\x18\x01 \x01(\x01R\x06factor\"9\n" +
	"\x18VideoSetCodecTypeRequest\x12\x1d\n" +
	"\n" +
	"codec_type\x18\x01 \x01(\x05R\tcodecType\":\n" +
	"\x19VideoGetCodecTypeResponse\x12\x1d\n" +
	"\n" +
	"codec_type\x18\x01 \x01(\x05R\tcodecType\")\n" +
	"\x13VideoSetEDIDRequest\x12\x12\n" +
	"\x04edid\x18\x01 \x01(\tR\x04edid\"*\n" +
	"\x14VideoGetEDIDResponse\x12\x12\n" +
	"\x04edid\x18\x01 \x01(\tR\x04edid\"0\n" +
	"\x16VideoLogStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"2\n" +
	"\x16GetLVGLVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"-\n" +
	"\x10UIObjHideRequest\x12\x19\n" +
	"\bobj_name\x18\x01 \x01(\tR\aobjName\"-\n" +
	"\x11UIObjHideResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x10UIObjShowRequest\x12\x19\n" +
	"\bobj_name\x18\x01 \x01(\tR\aobjName\"-\n" +
	"\x11UIObjShowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\";\n" +
	"\x0fUISetVarRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"%\n" +
	"\x0fUIGetVarRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"(\n" +
	"\x10UIGetVarResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"G\n" +
	"\x14UIObjAddStateRequest\x12\x19\n" +
	"\bobj_name\x18\x01 \x01(\tR\aobjName\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"1\n" +
	"\x15UIObjAddStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"I\n" +
	"\x16UIObjClearStateRequest\x12\x19\n" +
	"\bobj_name\x18\x01 \x01(\tR\aobjName\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"3\n" +
	"\x17UIObjClearStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"D\n" +
	"\x13UIObjAddFlagRequest\x12\x19\n" +
	"\bobj_name\x18\x01 \x01(\tR\aobjName\x12\x12\n" +
	"\x04flag\x18\x02 \x01(\tR\x04flag\"0\n" +
	"\x14UIObjAddFlagResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\x15UIObjClearFlagRequest\x12\x19\n" +
	"\bobj_name\x18\x01 \x01(\tR\aobjName\x12\x12\n" +
	"\x04flag\x18\x02 \x01(\tR\x04flag\"2\n" +
	"\x16UIObjClearFlagResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"M\n" +
	"\x16UIObjSetOpacityRequest\x12\x19\n" +
	"\bobj_name\x18\x01 \x01(\tR\aobjName\x12\x18\n" +
	"\aopacity\x18\x02 \x01(\x05R\aopacity\"3\n" +
	"\x17UIObjSetOpacityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"K\n" +
	"\x12UIObjFadeInRequest\x12\x19\n" +
	"\bobj_name\x18\x01 \x01(\tR\aobjName\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\rR\bduration\"/\n" +
	"\x13UIObjFadeInResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"L\n" +
	"\x13UIObjFadeOutRequest\x12\x19\n" +
	"\bobj_name\x18\x01 \x01(\tR\aobjName\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\rR\bduration\"0\n" +
	"\x14UIObjFadeOutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"I\n" +
	"\x18UIObjSetLabelTextRequest\x12\x19\n" +
	"\bobj_name\x18\x01 \x01(\tR\aobjName\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"5\n" +
	"\x19UIObjSetLabelTextResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"J\n" +
	"\x17UIObjSetImageSrcRequest\x12\x19\n" +
	"\bobj_name\x18\x01 \x01(\tR\aobjName\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\"4\n" +
	"\x18UIObjSetImageSrcResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"7\n" +
	"\x19DisplaySetRotationRequest\x12\x1a\n" +
	"\brotation\x18\x01 \x01(\rR\brotation\"6\n" +
	"\x1aDisplaySetRotationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"S\n" +
	"\x1bUpdateLabelIfChangedRequest\x12\x19\n" +
	"\bobj_name\x18\x01 \x01(\tR\aobjName\x12\x19\n" +
	"\bnew_text\x18\x02 \x01(\tR\anewText\"]\n" +
	"%UpdateLabelAndChangeVisibilityRequest\x12\x19\n" +
	"\bobj_name\x18\x01 \x01(\tR\aobjName\x12\x19\n" +
	"\bnew_text\x18\x02 \x01(\tR\anewText\"_\n" +
	"\x17SwitchToScreenIfRequest\x12\x1f\n" +
	"\vscreen_name\x18\x01 \x01(\tR\n" +
	"screenName\x12#\n" +
	"\rshould_switch\x18\x02 \x03(\tR\fshouldSwitch\"C\n" +
	" SwitchToScreenIfDifferentRequest\x12\x1f\n" +
	"\vscreen_name\x18\x01 \x01(\tR\n" +
	"screenName\"\xd3\x01\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x125\n" +
	"\vvideo_state\x18\x02 \x01(\v2\x12.native.VideoStateH\x00R\n" +
	"videoState\x12!\n" +
	"\vindev_event\x18\x03 \x01(\tH\x00R\n" +
	"indevEvent\x12\x1d\n" +
	"\trpc_event\x18\x04 \x01(\tH\x00R\brpcEvent\x125\n" +
	"\vvideo_frame\x18\x05 \x01(\v2\x12.native.VideoFrameH\x00R\n" +
	"videoFrameB\x06\n" +
	"\x04data\"C\n" +
	"\n" +
	"VideoFrame\x12\x14\n" +
	"\x05frame\x18\x01 \x01(\fR\x05frame\x12\x1f\n" +
	"\vduration_ns\x18\x02 \x01(\x03R\n" +
	"durationNs2\x8a\x13\n" +
	"\rNativeService\x12:\n" +
	"\aIsReady\x12\x16.native.IsReadyRequest\x1a\x17.native.IsReadyResponse\x12D\n" +
	"\x11VideoSetSleepMode\x12 .native.VideoSetSleepModeRequest\x1a\r.native.Empty\x12E\n" +
	"\x11VideoGetSleepMode\x12\r.native.Empty\x1a!.native.VideoGetSleepModeResponse\x12Q\n" +
	"\x17VideoSleepModeSupported\x12\r.native.Empty\x1a'.native.VideoSleepModeSupportedResponse\x12L\n" +
	"\x15VideoSetQualityFactor\x12$.native.VideoSetQualityFactorRequest\x1a\r.native.Empty\x12M\n" +
	"\x15VideoGetQualityFactor\x12\r.native.Empty\x1a%.native.VideoGetQualityFactorResponse\x12D\n" +
	"\x11VideoSetCodecType\x12 .native.VideoSetCodecTypeRequest\x1a\r.native.Empty\x12E\n" +
	"\x11VideoGetCodecType\x12\r.native.Empty\x1a!.native.VideoGetCodecTypeResponse\x12:\n" +
	"\fVideoSetEDID\x12\x1b.native.VideoSetEDIDRequest\x1a\r.native.Empty\x12;\n" +
	"\fVideoGetEDID\x12\r.native.Empty\x1a\x1c.native.VideoGetEDIDResponse\x12?\n" +
	"\x0eVideoLogStatus\x12\r.native.Empty\x1a\x1e.native.VideoLogStatusResponse\x12)\n" +
	"\tVideoStop\x12\r.native.Empty\x1a\r.native.Empty\x12*\n" +
	"\n" +
	"VideoStart\x12\r.native.Empty\x1a\r.native.Empty\x12?\n" +
	"\x0eGetLVGLVersion\x12\r.native.Empty\x1a\x1e.native.GetLVGLVersionResponse\x12@\n" +
	"\tUIObjHide\x12\x18.native.UIObjHideRequest\x1a\x19.native.UIObjHideResponse\x12@\n" +
	"\tUIObjShow\x12\x18.native.UIObjShowRequest\x1a\x19.native.UIObjShowResponse\x122\n" +
	"\bUISetVar\x12\x17.native.UISetVarRequest\x1a\r.native.Empty\x12=\n" +
	"\bUIGetVar\x12\x17.native.UIGetVarRequest\x1a\x18.native.UIGetVarResponse\x12L\n" +
	"\rUIObjAddState\x12\x1c.native.UIObjAddStateRequest\x1a\x1d.native.UIObjAddStateResponse\x12R\n" +
	"\x0fUIObjClearState\x12\x1e.native.UIObjClearStateRequest\x1a\x1f.native.UIObjClearStateResponse\x12I\n" +
	"\fUIObjAddFlag\x12\x1b.native.UIObjAddFlagRequest\x1a\x1c.native.UIObjAddFlagResponse\x12O\n" +
	"\x0eUIObjClearFlag\x12\x1d.native.UIObjClearFlagRequest\x1a\x1e.native.UIObjClearFlagResponse\x12R\n" +
	"\x0fUIObjSetOpacity\x12\x1e.native.UIObjSetOpacityRequest\x1a\x1f.native.UIObjSetOpacityResponse\x12F\n" +
	"\vUIObjFadeIn\x12\x1a.native.UIObjFadeInRequest\x1a\x1b.native.UIObjFadeInResponse\x12I\n" +
	"\fUIObjFadeOut\x12\x1b.native.UIObjFadeOutRequest\x1a\x1c.native.UIObjFadeOutResponse\x12X\n" +
	"\x11UIObjSetLabelText\x12 .native.UIObjSetLabelTextRequest\x1a!.native.UIObjSetLabelTextResponse\x12U\n" +
	"\x10UIObjSetImageSrc\x12\x1f.native.UIObjSetImageSrcRequest\x1a .native.UIObjSetImageSrcResponse\x12[\n" +
	"\x12DisplaySetRotation\x12!.native.DisplaySetRotationRequest\x1a\".native.DisplaySetRotationResponse\x12J\n" +
	"\x14UpdateLabelIfChanged\x12#.native.UpdateLabelIfChangedRequest\x1a\r.native.Empty\x12^\n" +
	"\x1eUpdateLabelAndChangeVisibility\x12-.native.UpdateLabelAndChangeVisibilityRequest\x1a\r.native.Empty\x12B\n" +
	"\x10SwitchToScreenIf\x12\x1f.native.SwitchToScreenIfRequest\x1a\r.native.Empty\x12T\n" +
	"\x19SwitchToScreenIfDifferent\x12(.native.SwitchToScreenIfDifferentRequest\x1a\r.native.Empty\x12A\n" +
	"!DoNotUseThisIsForCrashTestingOnly\x12\r.native.Empty\x1a\r.native.Empty\x12.\n" +
	"\fStreamEvents\x12\r.native.Empty\x1a\r.native.Event0\x01B-Z+github.com/jetkvm/kvm/internal/native/protob\x06proto3"

var (
	file_internal_native_proto_native_proto_rawDescOnce sync.Once
	file_internal_native_proto_native_proto_rawDescData []byte
)

func file_internal_native_proto_native_proto_rawDescGZIP() []byte {
	file_internal_native_proto_native_proto_rawDescOnce.Do(func() {
		file_internal_native_proto_native_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_native_proto_native_proto_rawDesc), len(file_internal_native_proto_native_proto_rawDesc)))
	})
	return file_internal_native_proto_native_proto_rawDescData
}

var file_internal_native_proto_native_proto_msgTypes = make([]protoimpl.MessageInfo, 48)
var file_internal_native_proto_native_proto_goTypes = []any{
	(*Empty)(nil),                                 // 0: native.Empty
	(*IsReadyRequest)(nil),                        // 1: native.IsReadyRequest
	(*IsReadyResponse)(nil),                       // 2: native.IsReadyResponse
	(*VideoState)(nil),                            // 3: native.VideoState
	(*VideoSetSleepModeRequest)(nil),              // 4: native.VideoSetSleepModeRequest
	(*VideoGetSleepModeResponse)(nil),             // 5: native.VideoGetSleepModeResponse
	(*VideoSleepModeSupportedResponse)(nil),       // 6: native.VideoSleepModeSupportedResponse
	(*VideoSetQualityFactorRequest)(nil),          // 7: native.VideoSetQualityFactorRequest
	(*VideoGetQualityFactorResponse)(nil),         // 8: native.VideoGetQualityFactorResponse
	(*VideoSetCodecTypeRequest)(nil),              // 9: native.VideoSetCodecTypeRequest
	(*VideoGetCodecTypeResponse)(nil),             // 10: native.VideoGetCodecTypeResponse
	(*VideoSetEDIDRequest)(nil),                   // 11: native.VideoSetEDIDRequest
	(*VideoGetEDIDResponse)(nil),                  // 12: native.VideoGetEDIDResponse
	(*VideoLogStatusResponse)(nil),                // 13: native.VideoLogStatusResponse
	(*GetLVGLVersionResponse)(nil),                // 14: native.GetLVGLVersionResponse
	(*UIObjHideRequest)(nil),                      // 15: native.UIObjHideRequest
	(*UIObjHideResponse)(nil),                     // 16: native.UIObjHideResponse
	(*UIObjShowRequest)(nil),                      // 17: native.UIObjShowRequest
	(*UIObjShowResponse)(nil),                     // 18: native.UIObjShowResponse
	(*UISetVarRequest)(nil),                       // 19: native.UISetVarRequest
	(*UIGetVarRequest)(nil),                       // 20: native.UIGetVarRequest
	(*UIGetVarResponse)(nil),                      // 21: native.UIGetVarResponse
	(*UIObjAddStateRequest)(nil),                  // 22: native.UIObjAddStateRequest
	(*UIObjAddStateResponse)(nil),                 // 23: native.UIObjAddStateResponse
	(*UIObjClearStateRequest)(nil),                // 24: native.UIObjClearStateRequest
	(*UIObjClearStateResponse)(nil),               // 25: native.UIObjClearStateResponse
	(*UIObjAddFlagRequest)(nil),                   // 26: native.UIObjAddFlagRequest
	(*UIObjAddFlagResponse)(nil),                  // 27: native.UIObjAddFlagResponse
	(*UIObjClearFlagRequest)(nil),                 // 28: native.UIObjClearFlagRequest
	(*UIObjClearFlagResponse)(nil),                // 29: native.UIObjClearFlagResponse
	(*UIObjSetOpacityRequest)(nil),                // 30: native.UIObjSetOpacityRequest
	(*UIObjSetOpacityResponse)(nil),               // 31: native.UIObjSetOpacityResponse
	(*UIObjFadeInRequest)(nil),                    // 32: native.UIObjFadeInRequest
	(*UIObjFadeInResponse)(nil),                   // 33: native.UIObjFadeInResponse
	(*UIObjFadeOutRequest)(nil),                   // 34: native.UIObjFadeOutRequest
	(*UIObjFadeOutResponse)(nil),                  // 35: native.UIObjFadeOutResponse
	(*UIObjSetLabelTextRequest)(nil),              // 36: native.UIObjSetLabelTextRequest
	(*UIObjSetLabelTextResponse)(nil),             // 37: native.UIObjSetLabelTextResponse
	(*UIObjSetImageSrcRequest)(nil),               // 38: native.UIObjSetImageSrcRequest
	(*UIObjSetImageSrcResponse)(nil),              // 39: native.UIObjSetImageSrcResponse
	(*DisplaySetRotationRequest)(nil),             // 40: native.DisplaySetRotationRequest
	(*DisplaySetRotationResponse)(nil),            // 41: native.DisplaySetRotationResponse
	(*UpdateLabelIfChangedRequest)(nil),           // 42: native.UpdateLabelIfChangedRequest
	(*UpdateLabelAndChangeVisibilityRequest)(nil), // 43: native.UpdateLabelAndChangeVisibilityRequest
	(*SwitchToScreenIfRequest)(nil),               // 44: native.SwitchToScreenIfRequest
	(*SwitchToScreenIfDifferentRequest)(nil),      // 45: native.SwitchToScreenIfDifferentRequest
	(*Event)(nil),                                 // 46: native.Event
	(*VideoFrame)(nil),                            // 47: native.VideoFrame
}
var file_internal_native_proto_native_proto_depIdxs = []int32{
	3,  // 0: native.Event.video_state:type_name -> native.VideoState
	47, // 1: native.Event.video_frame:type_name -> native.VideoFrame
	1,  // 2: native.NativeService.IsReady:input_type -> native.IsReadyRequest
	4,  // 3: native.NativeService.VideoSetSleepMode:input_type -> native.VideoSetSleepModeRequest
	0,  // 4: native.NativeService.VideoGetSleepMode:input_type -> native.Empty
	0,  // 5: native.NativeService.VideoSleepModeSupported:input_type -> native.Empty
	7,  // 6: native.NativeService.VideoSetQualityFactor:input_type -> native.VideoSetQualityFactorRequest
	0,  // 7: native.NativeService.VideoGetQualityFactor:input_type -> native.Empty
	9,  // 8: native.NativeService.VideoSetCodecType:input_type -> native.VideoSetCodecTypeRequest
	0,  // 9: native.NativeService.VideoGetCodecType:input_type -> native.Empty
	11, // 10: native.NativeService.VideoSetEDID:input_type -> native.VideoSetEDIDRequest
	0,  // 11: native.NativeService.VideoGetEDID:input_type -> native.Empty
	0,  // 12: native.NativeService.VideoLogStatus:input_type -> native.Empty
	0,  // 13: native.NativeService.VideoStop:input_type -> native.Empty
	0,  // 14: native.NativeService.VideoStart:input_type -> native.Empty
	0,  // 15: native.NativeService.GetLVGLVersion:input_type -> native.Empty
	15, // 16: native.NativeService.UIObjHide:input_type -> native.UIObjHideRequest
	17, // 17: native.NativeService.UIObjShow:input_type -> native.UIObjShowRequest
	19, // 18: native.NativeService.UISetVar:input_type -> native.UISetVarRequest
	20, // 19: native.NativeService.UIGetVar:input_type -> native.UIGetVarRequest
	22, // 20: native.NativeService.UIObjAddState:input_type -> native.UIObjAddStateRequest
	24, // 21: native.NativeService.UIObjClearState:input_type -> native.UIObjClearStateRequest
	26, // 22: native.NativeService.UIObjAddFlag:input_type -> native.UIObjAddFlagRequest
	28, // 23: native.NativeService.UIObjClearFlag:input_type -> native.UIObjClearFlagRequest
	30, // 24: native.NativeService.UIObjSetOpacity:input_type -> native.UIObjSetOpacityRequest
	32, // 25: native.NativeService.UIObjFadeIn:input_type -> native.UIObjFadeInRequest
	34, // 26: native.NativeService.UIObjFadeOut:input_type -> native.UIObjFadeOutRequest
	36, // 27: native.NativeService.UIObjSetLabelText:input_type -> native.UIObjSetLabelTextRequest
	38, // 28: native.NativeService.UIObjSetImageSrc:input_type -> native.UIObjSetImageSrcRequest
	40, // 29: native.NativeService.DisplaySetRotation:input_type -> native.DisplaySetRotationRequest
	42, // 30: native.NativeService.UpdateLabelIfChanged:input_type -> native.UpdateLabelIfChangedRequest
	43, // 31: native.NativeService.UpdateLabelAndChangeVisibility:input_type -> native.UpdateLabelAndChangeVisibilityRequest
	44, // 32: native.NativeService.SwitchToScreenIf:input_type -> native.SwitchToScreenIfRequest
	45, // 33: native.NativeService.SwitchToScreenIfDifferent:input_type -> native.SwitchToScreenIfDifferentRequest
	0,  // 34: native.NativeService.DoNotUseThisIsForCrashTestingOnly:input_type -> native.Empty
	0,  // 35: native.NativeService.StreamEvents:input_type -> native.Empty
	2,  // 36: native.NativeService.IsReady:output_type -> native.IsReadyResponse
	0,  // 37: native.NativeService.VideoSetSleepMode:output_type -> native.Empty
	5,  // 38: native.NativeService.VideoGetSleepMode:output_type -> native.VideoGetSleepModeResponse
	6,  // 39: native.NativeService.VideoSleepModeSupported:output_type -> native.VideoSleepModeSupportedResponse
	0,  // 40: native.NativeService.VideoSetQualityFactor:output_type -> native.Empty
	8,  // 41: native.NativeService.VideoGetQualityFactor:output_type -> native.VideoGetQualityFactorResponse
	0,  // 42: native.NativeService.VideoSetCodecType:output_type -> native.Empty
	10, // 43: native.NativeService.VideoGetCodecType:output_type -> native.VideoGetCodecTypeResponse
	0,  // 44: native.NativeService.VideoSetEDID:output_type -> native.Empty
	12, // 45: native.NativeService.VideoGetEDID:output_type -> native.VideoGetEDIDResponse
	13, // 46: native.NativeService.VideoLogStatus:output_type -> native.VideoLogStatusResponse
	0,  // 47: native.NativeService.VideoStop:output_type -> native.Empty
	0,  // 48: native.NativeService.VideoStart:output_type -> native.Empty
	14, // 49: native.NativeService.GetLVGLVersion:output_type -> native.GetLVGLVersionResponse
	16, // 50: native.NativeService.UIObjHide:output_type -> native.UIObjHideResponse
	18, // 51: native.NativeService.UIObjShow:output_type -> native.UIObjShowResponse
	0,  // 52: native.NativeService.UISetVar:output_type -> native.Empty
	21, // 53: native.NativeService.UIGetVar:output_type -> native.UIGetVarResponse
	23, // 54: native.NativeService.UIObjAddState:output_type -> native.UIObjAddStateResponse
	25, // 55: native.NativeService.UIObjClearState:output_type -> native.UIObjClearStateResponse
	27, // 56: native.NativeService.UIObjAddFlag:output_type -> native.UIObjAddFlagResponse
	29, // 57: native.NativeService.UIObjClearFlag:output_type -> native.UIObjClearFlagResponse
	31, // 58: native.NativeService.UIObjSetOpacity:output_type -> native.UIObjSetOpacityResponse
	33, // 59: native.NativeService.UIObjFadeIn:output_type -> native.UIObjFadeInResponse
	35, // 60: native.NativeService.UIObjFadeOut:output_type -> native.UIObjFadeOutResponse
	37, // 61: native.NativeService.UIObjSetLabelText:output_type -> native.UIObjSetLabelTextResponse
	39, // 62: native.NativeService.UIObjSetImageSrc:output_type -> native.UIObjSetImageSrcResponse
	41, // 63: native.NativeService.DisplaySetRotation:output_type -> native.DisplaySetRotationResponse
	0,  // 64: native.NativeService.UpdateLabelIfChanged:output_type -> native.Empty
	0,  // 65: native.NativeService.UpdateLabelAndChangeVisibility:output_type -> native.Empty
	0,  // 66: native.NativeService.SwitchToScreenIf:output_type -> native.Empty
	0,  // 67: native.NativeService.SwitchToScreenIfDifferent:output_type -> native.Empty
	0,  // 68: native.NativeService.DoNotUseThisIsForCrashTestingOnly:output_type -> native.Empty
	46, // 69: native.NativeService.StreamEvents:output_type -> native.Event
	36, // [36:70] is the sub-list for method output_type
	2,  // [2:36] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_internal_native_proto_native_proto_init() }
func file_internal_native_proto_native_proto_init() {
	if File_internal_native_proto_native_proto != nil {
		return
	}
	file_internal_native_proto_native_proto_msgTypes[46].OneofWrappers = []any{
		(*Event_VideoState)(nil),
		(*Event_IndevEvent)(nil),
		(*Event_RpcEvent)(nil),
		(*Event_VideoFrame)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_native_proto_native_proto_rawDesc), len(file_internal_native_proto_native_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   48,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_native_proto_native_proto_goTypes,
		DependencyIndexes: file_internal_native_proto_native_proto_depIdxs,
		MessageInfos:      file_internal_native_proto_native_proto_msgTypes,
	}.Build()
	File_internal_native_proto_native_proto = out.File
	file_internal_native_proto_native_proto_goTypes = nil
	file_internal_native_proto_native_proto_depIdxs = nil
}
