// Code generated by protoc-gen-go. DO NOT EDIT.
// This file should be regenerated from native.proto using:
//   protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative internal/native/proto/native.proto
//
// For now, this is a minimal implementation to allow compilation.
// TODO: Regenerate from proto file when protoc is available.

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
}

func (x *Empty) String() string {
	return ""
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	return nil // Stub
}

type VideoState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ready          bool    `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Error          string  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Width          int32   `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height         int32   `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	FramePerSecond float64 `protobuf:"fixed64,5,opt,name=frame_per_second,json=framePerSecond,proto3" json:"frame_per_second,omitempty"`
}

func (x *VideoState) Reset() {
	*x = VideoState{}
}

func (x *VideoState) String() string {
	return ""
}

func (*VideoState) ProtoMessage() {}

func (x *VideoState) ProtoReflect() protoreflect.Message {
	return nil // Stub
}

// Request/Response types - minimal implementations
type VideoSetSleepModeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Enabled       bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *VideoSetSleepModeRequest) Reset()                             { *x = VideoSetSleepModeRequest{} }
func (x *VideoSetSleepModeRequest) String() string                     { return "" }
func (*VideoSetSleepModeRequest) ProtoMessage()                        {}
func (x *VideoSetSleepModeRequest) ProtoReflect() protoreflect.Message { return nil }

type VideoGetSleepModeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Enabled       bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *VideoGetSleepModeResponse) Reset()                             { *x = VideoGetSleepModeResponse{} }
func (x *VideoGetSleepModeResponse) String() string                     { return "" }
func (*VideoGetSleepModeResponse) ProtoMessage()                        {}
func (x *VideoGetSleepModeResponse) ProtoReflect() protoreflect.Message { return nil }

type VideoSleepModeSupportedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Supported     bool `protobuf:"varint,1,opt,name=supported,proto3" json:"supported,omitempty"`
}

func (x *VideoSleepModeSupportedResponse) Reset()                             { *x = VideoSleepModeSupportedResponse{} }
func (x *VideoSleepModeSupportedResponse) String() string                     { return "" }
func (*VideoSleepModeSupportedResponse) ProtoMessage()                        {}
func (x *VideoSleepModeSupportedResponse) ProtoReflect() protoreflect.Message { return nil }

type VideoSetQualityFactorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Factor        float64 `protobuf:"fixed64,1,opt,name=factor,proto3" json:"factor,omitempty"`
}

func (x *VideoSetQualityFactorRequest) Reset()                             { *x = VideoSetQualityFactorRequest{} }
func (x *VideoSetQualityFactorRequest) String() string                     { return "" }
func (*VideoSetQualityFactorRequest) ProtoMessage()                        {}
func (x *VideoSetQualityFactorRequest) ProtoReflect() protoreflect.Message { return nil }

type VideoGetQualityFactorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Factor        float64 `protobuf:"fixed64,1,opt,name=factor,proto3" json:"factor,omitempty"`
}

func (x *VideoGetQualityFactorResponse) Reset()                             { *x = VideoGetQualityFactorResponse{} }
func (x *VideoGetQualityFactorResponse) String() string                     { return "" }
func (*VideoGetQualityFactorResponse) ProtoMessage()                        {}
func (x *VideoGetQualityFactorResponse) ProtoReflect() protoreflect.Message { return nil }

type VideoSetEDIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Edid          string `protobuf:"bytes,1,opt,name=edid,proto3" json:"edid,omitempty"`
}

func (x *VideoSetEDIDRequest) Reset()                             { *x = VideoSetEDIDRequest{} }
func (x *VideoSetEDIDRequest) String() string                     { return "" }
func (*VideoSetEDIDRequest) ProtoMessage()                        {}
func (x *VideoSetEDIDRequest) ProtoReflect() protoreflect.Message { return nil }

type VideoGetEDIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Edid          string `protobuf:"bytes,1,opt,name=edid,proto3" json:"edid,omitempty"`
}

func (x *VideoGetEDIDResponse) Reset()                             { *x = VideoGetEDIDResponse{} }
func (x *VideoGetEDIDResponse) String() string                     { return "" }
func (*VideoGetEDIDResponse) ProtoMessage()                        {}
func (x *VideoGetEDIDResponse) ProtoReflect() protoreflect.Message { return nil }

type VideoLogStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *VideoLogStatusResponse) Reset()                             { *x = VideoLogStatusResponse{} }
func (x *VideoLogStatusResponse) String() string                     { return "" }
func (*VideoLogStatusResponse) ProtoMessage()                        {}
func (x *VideoLogStatusResponse) ProtoReflect() protoreflect.Message { return nil }

type GetLVGLVersionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Version       string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *GetLVGLVersionResponse) Reset()                             { *x = GetLVGLVersionResponse{} }
func (x *GetLVGLVersionResponse) String() string                     { return "" }
func (*GetLVGLVersionResponse) ProtoMessage()                        {}
func (x *GetLVGLVersionResponse) ProtoReflect() protoreflect.Message { return nil }

// UI message types
type UIObjHideRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	ObjName       string `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
}

func (x *UIObjHideRequest) Reset()                             { *x = UIObjHideRequest{} }
func (x *UIObjHideRequest) String() string                     { return "" }
func (*UIObjHideRequest) ProtoMessage()                        {}
func (x *UIObjHideRequest) ProtoReflect() protoreflect.Message { return nil }

type UIObjHideResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UIObjHideResponse) Reset()                             { *x = UIObjHideResponse{} }
func (x *UIObjHideResponse) String() string                     { return "" }
func (*UIObjHideResponse) ProtoMessage()                        {}
func (x *UIObjHideResponse) ProtoReflect() protoreflect.Message { return nil }

type UIObjShowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	ObjName       string `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
}

func (x *UIObjShowRequest) Reset()                             { *x = UIObjShowRequest{} }
func (x *UIObjShowRequest) String() string                     { return "" }
func (*UIObjShowRequest) ProtoMessage()                        {}
func (x *UIObjShowRequest) ProtoReflect() protoreflect.Message { return nil }

type UIObjShowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UIObjShowResponse) Reset()                             { *x = UIObjShowResponse{} }
func (x *UIObjShowResponse) String() string                     { return "" }
func (*UIObjShowResponse) ProtoMessage()                        {}
func (x *UIObjShowResponse) ProtoReflect() protoreflect.Message { return nil }

type UISetVarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UISetVarRequest) Reset()                             { *x = UISetVarRequest{} }
func (x *UISetVarRequest) String() string                     { return "" }
func (*UISetVarRequest) ProtoMessage()                        {}
func (x *UISetVarRequest) ProtoReflect() protoreflect.Message { return nil }

type UIGetVarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UIGetVarRequest) Reset()                             { *x = UIGetVarRequest{} }
func (x *UIGetVarRequest) String() string                     { return "" }
func (*UIGetVarRequest) ProtoMessage()                        {}
func (x *UIGetVarRequest) ProtoReflect() protoreflect.Message { return nil }

type UIGetVarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Value         string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UIGetVarResponse) Reset()                             { *x = UIGetVarResponse{} }
func (x *UIGetVarResponse) String() string                     { return "" }
func (*UIGetVarResponse) ProtoMessage()                        {}
func (x *UIGetVarResponse) ProtoReflect() protoreflect.Message { return nil }

// Additional UI types - abbreviated for brevity, follow same pattern
type UIObjAddStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	ObjName       string `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	State         string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *UIObjAddStateRequest) Reset()                             { *x = UIObjAddStateRequest{} }
func (x *UIObjAddStateRequest) String() string                     { return "" }
func (*UIObjAddStateRequest) ProtoMessage()                        {}
func (x *UIObjAddStateRequest) ProtoReflect() protoreflect.Message { return nil }

type UIObjAddStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UIObjAddStateResponse) Reset()                             { *x = UIObjAddStateResponse{} }
func (x *UIObjAddStateResponse) String() string                     { return "" }
func (*UIObjAddStateResponse) ProtoMessage()                        {}
func (x *UIObjAddStateResponse) ProtoReflect() protoreflect.Message { return nil }

// Event types
type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Type          string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// oneof data - using separate fields for now
	VideoState *VideoState `protobuf:"bytes,2,opt,name=video_state,json=videoState,proto3" json:"video_state,omitempty"`
	IndevEvent string      `protobuf:"bytes,3,opt,name=indev_event,json=indevEvent,proto3" json:"indev_event,omitempty"`
	RpcEvent   string      `protobuf:"bytes,4,opt,name=rpc_event,json=rpcEvent,proto3" json:"rpc_event,omitempty"`
	VideoFrame *VideoFrame `protobuf:"bytes,5,opt,name=video_frame,json=videoFrame,proto3" json:"video_frame,omitempty"`
}

func (x *Event) Reset()                             { *x = Event{} }
func (x *Event) String() string                     { return "" }
func (*Event) ProtoMessage()                        {}
func (x *Event) ProtoReflect() protoreflect.Message { return nil }

type VideoFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Frame         []byte `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"`
	DurationNs    int64  `protobuf:"varint,2,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
}

func (x *VideoFrame) Reset()                             { *x = VideoFrame{} }
func (x *VideoFrame) String() string                     { return "" }
func (*VideoFrame) ProtoMessage()                        {}
func (x *VideoFrame) ProtoReflect() protoreflect.Message { return nil }

// Additional request/response types - following same pattern
// (Abbreviated - all follow the same structure)
type UIObjClearStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	ObjName       string `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	State         string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *UIObjClearStateRequest) Reset()                             { *x = UIObjClearStateRequest{} }
func (x *UIObjClearStateRequest) String() string                     { return "" }
func (*UIObjClearStateRequest) ProtoMessage()                        {}
func (x *UIObjClearStateRequest) ProtoReflect() protoreflect.Message { return nil }

type UIObjClearStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UIObjClearStateResponse) Reset()                             { *x = UIObjClearStateResponse{} }
func (x *UIObjClearStateResponse) String() string                     { return "" }
func (*UIObjClearStateResponse) ProtoMessage()                        {}
func (x *UIObjClearStateResponse) ProtoReflect() protoreflect.Message { return nil }

// Remaining types follow same pattern - creating minimal stubs
// TODO: Regenerate from proto for complete implementation

type UIObjAddFlagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	ObjName       string `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	Flag          string `protobuf:"bytes,2,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *UIObjAddFlagRequest) Reset()                             { *x = UIObjAddFlagRequest{} }
func (x *UIObjAddFlagRequest) String() string                     { return "" }
func (*UIObjAddFlagRequest) ProtoMessage()                        {}
func (x *UIObjAddFlagRequest) ProtoReflect() protoreflect.Message { return nil }

type UIObjAddFlagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UIObjAddFlagResponse) Reset()                             { *x = UIObjAddFlagResponse{} }
func (x *UIObjAddFlagResponse) String() string                     { return "" }
func (*UIObjAddFlagResponse) ProtoMessage()                        {}
func (x *UIObjAddFlagResponse) ProtoReflect() protoreflect.Message { return nil }

type UIObjClearFlagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	ObjName       string `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	Flag          string `protobuf:"bytes,2,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *UIObjClearFlagRequest) Reset()                             { *x = UIObjClearFlagRequest{} }
func (x *UIObjClearFlagRequest) String() string                     { return "" }
func (*UIObjClearFlagRequest) ProtoMessage()                        {}
func (x *UIObjClearFlagRequest) ProtoReflect() protoreflect.Message { return nil }

type UIObjClearFlagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UIObjClearFlagResponse) Reset()                             { *x = UIObjClearFlagResponse{} }
func (x *UIObjClearFlagResponse) String() string                     { return "" }
func (*UIObjClearFlagResponse) ProtoMessage()                        {}
func (x *UIObjClearFlagResponse) ProtoReflect() protoreflect.Message { return nil }

type UIObjSetOpacityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	ObjName       string `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	Opacity       int32  `protobuf:"varint,2,opt,name=opacity,proto3" json:"opacity,omitempty"`
}

func (x *UIObjSetOpacityRequest) Reset()                             { *x = UIObjSetOpacityRequest{} }
func (x *UIObjSetOpacityRequest) String() string                     { return "" }
func (*UIObjSetOpacityRequest) ProtoMessage()                        {}
func (x *UIObjSetOpacityRequest) ProtoReflect() protoreflect.Message { return nil }

type UIObjSetOpacityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UIObjSetOpacityResponse) Reset()                             { *x = UIObjSetOpacityResponse{} }
func (x *UIObjSetOpacityResponse) String() string                     { return "" }
func (*UIObjSetOpacityResponse) ProtoMessage()                        {}
func (x *UIObjSetOpacityResponse) ProtoReflect() protoreflect.Message { return nil }

type UIObjFadeInRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	ObjName       string `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	Duration      uint32 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *UIObjFadeInRequest) Reset()                             { *x = UIObjFadeInRequest{} }
func (x *UIObjFadeInRequest) String() string                     { return "" }
func (*UIObjFadeInRequest) ProtoMessage()                        {}
func (x *UIObjFadeInRequest) ProtoReflect() protoreflect.Message { return nil }

type UIObjFadeInResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UIObjFadeInResponse) Reset()                             { *x = UIObjFadeInResponse{} }
func (x *UIObjFadeInResponse) String() string                     { return "" }
func (*UIObjFadeInResponse) ProtoMessage()                        {}
func (x *UIObjFadeInResponse) ProtoReflect() protoreflect.Message { return nil }

type UIObjFadeOutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	ObjName       string `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	Duration      uint32 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *UIObjFadeOutRequest) Reset()                             { *x = UIObjFadeOutRequest{} }
func (x *UIObjFadeOutRequest) String() string                     { return "" }
func (*UIObjFadeOutRequest) ProtoMessage()                        {}
func (x *UIObjFadeOutRequest) ProtoReflect() protoreflect.Message { return nil }

type UIObjFadeOutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UIObjFadeOutResponse) Reset()                             { *x = UIObjFadeOutResponse{} }
func (x *UIObjFadeOutResponse) String() string                     { return "" }
func (*UIObjFadeOutResponse) ProtoMessage()                        {}
func (x *UIObjFadeOutResponse) ProtoReflect() protoreflect.Message { return nil }

type UIObjSetLabelTextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	ObjName       string `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *UIObjSetLabelTextRequest) Reset()                             { *x = UIObjSetLabelTextRequest{} }
func (x *UIObjSetLabelTextRequest) String() string                     { return "" }
func (*UIObjSetLabelTextRequest) ProtoMessage()                        {}
func (x *UIObjSetLabelTextRequest) ProtoReflect() protoreflect.Message { return nil }

type UIObjSetLabelTextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UIObjSetLabelTextResponse) Reset()                             { *x = UIObjSetLabelTextResponse{} }
func (x *UIObjSetLabelTextResponse) String() string                     { return "" }
func (*UIObjSetLabelTextResponse) ProtoMessage()                        {}
func (x *UIObjSetLabelTextResponse) ProtoReflect() protoreflect.Message { return nil }

type UIObjSetImageSrcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	ObjName       string `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	Image         string `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *UIObjSetImageSrcRequest) Reset()                             { *x = UIObjSetImageSrcRequest{} }
func (x *UIObjSetImageSrcRequest) String() string                     { return "" }
func (*UIObjSetImageSrcRequest) ProtoMessage()                        {}
func (x *UIObjSetImageSrcRequest) ProtoReflect() protoreflect.Message { return nil }

type UIObjSetImageSrcResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UIObjSetImageSrcResponse) Reset()                             { *x = UIObjSetImageSrcResponse{} }
func (x *UIObjSetImageSrcResponse) String() string                     { return "" }
func (*UIObjSetImageSrcResponse) ProtoMessage()                        {}
func (x *UIObjSetImageSrcResponse) ProtoReflect() protoreflect.Message { return nil }

type DisplaySetRotationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Rotation      uint32 `protobuf:"varint,1,opt,name=rotation,proto3" json:"rotation,omitempty"`
}

func (x *DisplaySetRotationRequest) Reset()                             { *x = DisplaySetRotationRequest{} }
func (x *DisplaySetRotationRequest) String() string                     { return "" }
func (*DisplaySetRotationRequest) ProtoMessage()                        {}
func (x *DisplaySetRotationRequest) ProtoReflect() protoreflect.Message { return nil }

type DisplaySetRotationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DisplaySetRotationResponse) Reset()                             { *x = DisplaySetRotationResponse{} }
func (x *DisplaySetRotationResponse) String() string                     { return "" }
func (*DisplaySetRotationResponse) ProtoMessage()                        {}
func (x *DisplaySetRotationResponse) ProtoReflect() protoreflect.Message { return nil }

type UpdateLabelIfChangedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	ObjName       string `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	NewText       string `protobuf:"bytes,2,opt,name=new_text,json=newText,proto3" json:"new_text,omitempty"`
}

func (x *UpdateLabelIfChangedRequest) Reset()                             { *x = UpdateLabelIfChangedRequest{} }
func (x *UpdateLabelIfChangedRequest) String() string                     { return "" }
func (*UpdateLabelIfChangedRequest) ProtoMessage()                        {}
func (x *UpdateLabelIfChangedRequest) ProtoReflect() protoreflect.Message { return nil }

type UpdateLabelAndChangeVisibilityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	ObjName       string `protobuf:"bytes,1,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	NewText       string `protobuf:"bytes,2,opt,name=new_text,json=newText,proto3" json:"new_text,omitempty"`
}

func (x *UpdateLabelAndChangeVisibilityRequest) Reset()                             { *x = UpdateLabelAndChangeVisibilityRequest{} }
func (x *UpdateLabelAndChangeVisibilityRequest) String() string                     { return "" }
func (*UpdateLabelAndChangeVisibilityRequest) ProtoMessage()                        {}
func (x *UpdateLabelAndChangeVisibilityRequest) ProtoReflect() protoreflect.Message { return nil }

type SwitchToScreenIfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	ScreenName    string   `protobuf:"bytes,1,opt,name=screen_name,json=screenName,proto3" json:"screen_name,omitempty"`
	ShouldSwitch  []string `protobuf:"bytes,2,rep,name=should_switch,json=shouldSwitch,proto3" json:"should_switch,omitempty"`
}

func (x *SwitchToScreenIfRequest) Reset()                             { *x = SwitchToScreenIfRequest{} }
func (x *SwitchToScreenIfRequest) String() string                     { return "" }
func (*SwitchToScreenIfRequest) ProtoMessage()                        {}
func (x *SwitchToScreenIfRequest) ProtoReflect() protoreflect.Message { return nil }

type SwitchToScreenIfDifferentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	ScreenName    string `protobuf:"bytes,1,opt,name=screen_name,json=screenName,proto3" json:"screen_name,omitempty"`
}

func (x *SwitchToScreenIfDifferentRequest) Reset()                             { *x = SwitchToScreenIfDifferentRequest{} }
func (x *SwitchToScreenIfDifferentRequest) String() string                     { return "" }
func (*SwitchToScreenIfDifferentRequest) ProtoMessage()                        {}
func (x *SwitchToScreenIfDifferentRequest) ProtoReflect() protoreflect.Message { return nil }
